# Setup

esphome:
  name: silviaesp32
  platform: ESP32
  board: nodemcu-32s
  includes:
    - UartReadLineSensor.h

wifi:
  # Replace with your Wifi SSID:
  ssid: "emiladhoc"
  # Replace with your Wifi password:
  password: "coffeetime"
  power_save_mode: none

# Uncomment to assign a static IP if necessary:
#  manual_ip:
#    static_ip: x.x.x.x
#    gateway: x.x.x.x
#    subnet: 255.255.255.0

  ap:  # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "silviaesp32"
    password: "ineedhelp"

captive_portal:

# Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

# Enable Home Assistant API
api:
  password: "coffeetime"

ota:
  password: "coffeetime"
  safe_mode: False
  num_attempts: 100

# Font
font:
  - file: "poppinsMedium.ttf"
    id: sys_font
    size: 20

# Inputs

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 500000

binary_sensor:
  - platform: gpio
    pin:
      number: 25
      mode: INPUT_PULLUP
    name: "Steam Switch"
    id: steamSwitch

  - platform: gpio
    pin:
      number: 26
      mode: INPUT_PULLUP
    name: "Hot Water Switch"
    id: hotWaterSwitch

  - platform: gpio
    pin:
      number: 33
      mode: INPUT_PULLUP
    name: "Brew Switch"
    id: brewSwitch

sensor:
  - platform: adc
    pin: 35 
    attenuation: 11db
    name: "Pressure"
    id: pressure
    update_interval: 1s # change to Xs when finalizing
    unit_of_measurement: Bar
    filters:
      - multiply: 1 # May change depending on transducer/current adapter

  - platform: pulse_width
    pin: 14
    update_interval: 1s
    name: "Group Head PWM Link"
    id: groupHeadPWMLink
    filters:
     - multiply: 0.1


  - platform: pulse_width
    pin: 12 
    update_interval: 1s
    name: "Boiler PWM Link"
    id: boilerPWMLink
    filters:
     - multiply: 0.1

# Processing

climate:
  - platform: pid
    name: "PID Controller"
    sensor: groupHeadPWMLink
    default_target_temperature: 100°C
    heat_output: boilerSSR
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301

# Outputs

i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: ssd1306_i2c # SSD1306 pinouts vary
    model: "SSD1306 128x64"
    #reset_pin: 0
    #address: 0x3c
    lambda: |-
      it.printf(0, 0, id(sys_font), "temp: %.01f", id(groupHeadPWMLink).state);
      it.printf(0, 22, id(sys_font), "bar: %.01f", id(pressure).state);

switch:
  - platform: restart
    name: "Restart ESP"

light:
  - platform: monochromatic
    output: pump
    name: Phase Angle Pump

output:
  - platform: ac_dimmer
    id: pump
    gate_pin: GPIO19
    zero_cross_pin:
      number: GPIO18
      mode: INPUT
      inverted: yes

  - platform: slow_pwm
    pin: GPIO27
    id: boilerSSR
    period: 100ms
