# Setup

esphome:
  name: silviaesp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  # Replace with your Wifi SSID:
  ssid: "emiladhoc"
  # Replace with your Wifi password:
  password: "coffeetime"
  power_save_mode: none

# Uncomment to assign a static IP if necessary:
#  manual_ip:
#    static_ip: x.x.x.x
#    gateway: x.x.x.x
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "silviaesp32"
    password: "ineedhelp"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "coffeetime"

ota:
  password: "coffeetime"
  safe_mode: False
  num_attempts: 100

# Font
font:
  - file: "poppinsMedium.ttf"
    id: sys_font
    size: 20

# Inputs

switch:
  - platform: restart
    name: "Restart ESP"

  - platform: gpio
    pin: 33
    name: "Digital Out 33"

sensor:

  - platform: adc
    pin: 34
    attenuation: 11db
    name: "Pressure"
    id: pressure
    update_interval: 5s # change to Xs when finalizing
    unit_of_measurement: Bar
    filters:
      - multiply: 1 # May change depending on transducer/current adapter

# Outputs

i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: ssd1306_i2c # SSD1306 pinouts vary
    model: "SSD1306 128x64"
    #reset_pin: 0
    #address: 0x3c
    lambda: |-
      it.printf(0, 0, id(sys_font), "grams: %.01f", id(pressure).state);
      it.printf(0, 22, id(sys_font), "bar: %.01f", id(pressure).state);

output:
  - platform: ac_dimmer
    id: pump
    gate_pin: GPIO19
    zero_cross_pin:
      number: GPIO35
      mode: INPUT
      inverted: yes

light:
  - platform: monochromatic
    output: pump
    name: Phase Angle Pump