# Setup

esphome:
  name: silviaesp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  # Replace with your Wifi SSID:
  ssid: "emiladhoc"
  # Replace with your Wifi password:
  password: "coffeetime"
  power_save_mode: none

# Uncomment to assign a static IP if necessary:
#  manual_ip:
#    static_ip: x.x.x.x
#    gateway: x.x.x.x
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "silviaesp32"
    password: "ineedhelp"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "coffeetime"

ota:
  password: "coffeetime"
  safe_mode: False
  num_attempts: 100

# Font
font:
  - file: "poppinsMedium.ttf"
    id: sys_font
    size: 20

# Inputs

switch:
  - platform: restart
    name: "Restart ESP"

  - platform: gpio
    pin: 33
    name: "Living Room Dehumidifier"

sensor:
  - platform: pulse_counter
    pin: 12
    name: "Gicar"
    id: flow
    unit_of_measurement: "mL/s"
    update_interval: 60s # change to 1s when finalizing
    filters:
      - lambda: return x / 60;

binary_sensor:
  - platform: ble_presence # Commenting out this sensor will make the ESP look for BLE devices
    mac_address: C5:71:4A:8B:10:D3 # Put your skale's MAC here 
    name: "Skale II"
    id: skaleii

# Outputs

i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: ssd1306_i2c # SSD1306 pinouts vary
    model: "SSD1306 128x64"
    #reset_pin: 0
    #address: 0x3c
    lambda: |-
      it.printf(0, 0, id(sys_font), "is: %.1f", id(flow).state);

esp32_ble_tracker:

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO19
    zero_cross_pin:
      number: GPIO35
      mode: INPUT
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer1
    name: Phase Angle Pump