esphome:
  name: silviaesp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "emiladhoc"
  password: "coffeetime"
  power_save_mode: none

#  manual_ip:
#    static_ip: x.x.x.x
#    gateway: x.x.x.x
#    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "silviaesphotspot"
    password: "blahblah"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "coffeetime"

ota:
  password: "coffeetime"
