# Setup

esphome:
  name: silviaesp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  # Replace with your Wifi SSID:
  ssid: "emiladhoc"
  # Replace with your Wifi password:
  password: "coffeetime"
  power_save_mode: none

# Uncomment to assign a static IP if necessary:
#  manual_ip:
#    static_ip: x.x.x.x
#    gateway: x.x.x.x
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "silviaesp32"
    password: "ineedhelp"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "coffeetime"

ota:
  password: "coffeetime"
  safe_mode: False
  num_attempts: 100

# Inputs

switch:
  - platform: restart
    name: "Restart ESP"

# Outputs

i2c:
  sda: GPIO21
  scl: GPIO22

font:
  - file: "ComicSans.ttf"
    id: cool_font
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    # If the ESP can't find the display over I2C uncommenting these might help
    #reset_pin: D0
    #address: 0x3c
    lambda: |-
      it.print(0, 0, id(cool_font), "Hello World!");